project_name: cf-tool

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: cf

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: XCPCIO
    name: cf-tool
