project_name: cf-tool

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    binary: cf

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Dup4
    name: cf-tool

changelog:
  use: github
  sort: asc

  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Refactor"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: "Test"
      regexp: "^.*test[(\\w)]*:+.*$"
      order: 3

  filters:
    exclude:
      - "^docs"
      - "^style"
      - "^chore"
